version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-0.10.2.1
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      # KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_MACHINE_IP}"
      # KAFKA_ADVERTISED_HOST_NAME: kafka
      # KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # kafka-manager:
  #   image: andreformento/docker-kafka-manager
  #   ports:
  #     - "9000:9000"
  #   links:
  #     - zookeeper
  #     - kafka
  #   command: ["-Dconfig.file=conf/application.conf", "-Dkafka-manager.zkhosts=zookeeper:2181"]
